[package]
name = "citadel-client"
version = "0.1.0"
edition = "2021"

[dependencies]
guard-net = { path = "../guard-net" }
guard-svc = { path = "../guard-svc" }
windows = { version = "0.58", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }
